/*
 * Created on 2021-10-19 ( 12:45:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.jpa.data;

import javax.persistence.EntityManager;

import com.mindia.carmind.entities.Empresas;

public class EmpresasData {

	private static Empresas entity ;

    public static void init(EntityManager em) {
    	// new entity instance
    	Empresas newEntity = new Empresas();
		newEntity.setId( Integer.valueOf(100) ) ;
		newEntity.setNombre( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;

		// save entity in database
        em.getTransaction().begin();
        Empresas managedEntity = (Empresas) em.merge(newEntity);
        em.getTransaction().commit();
        entity = managedEntity;
    }
	
    public static Empresas getEntity() {
    	return entity;
    }
}
