/*
 * Created on 2021-10-19 ( 12:45:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.jpa.data;

import javax.persistence.EntityManager;

import com.mindia.carmind.entities.Evaluaciones;

public class EvaluacionesData {

	private static Evaluaciones entity ;

    public static void init(EntityManager em) {
    	// new entity instance
    	Evaluaciones newEntity = new Evaluaciones();
		newEntity.setId( Integer.valueOf(100) ) ;
		newEntity.setIdentificador( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;

		// save entity in database
        em.getTransaction().begin();
        Evaluaciones managedEntity = (Evaluaciones) em.merge(newEntity);
        em.getTransaction().commit();
        entity = managedEntity;
    }
	
    public static Evaluaciones getEntity() {
    	return entity;
    }
}
