/*
 * Created on 2021-10-19 ( 12:45:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.jpa.data;

import javax.persistence.EntityManager;

import com.mindia.carmind.entities.LogEvaluaciones;

public class LogEvaluacionesData {

	private static LogEvaluaciones entity ;

    public static void init(EntityManager em) {
    	// new entity instance
    	LogEvaluaciones newEntity = new LogEvaluaciones();
		newEntity.setId( Integer.valueOf(100) ) ;
		newEntity.setFecha( java.sql.Date.valueOf("2001-06-22") ) ;
		newEntity.setEvaluacion( Integer.valueOf(100) ) ;

		// save entity in database
        em.getTransaction().begin();
        LogEvaluaciones managedEntity = (LogEvaluaciones) em.merge(newEntity);
        em.getTransaction().commit();
        entity = managedEntity;
    }
	
    public static LogEvaluaciones getEntity() {
    	return entity;
    }
}
