/*
 * Created on 2021-10-19 ( 12:45:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.jpa.data;

import javax.persistence.EntityManager;

import com.mindia.carmind.entities.LogPreguntas;

public class LogPreguntasData {

	private static LogPreguntas entity ;

    public static void init(EntityManager em) {
    	// new entity instance
    	LogPreguntas newEntity = new LogPreguntas();
		newEntity.setId( Integer.valueOf(100) ) ;
		newEntity.setLogEvaluacion( Integer.valueOf(100) ) ;
		newEntity.setPregunta( Integer.valueOf(100) ) ;
		newEntity.setRespuesta( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;

		// save entity in database
        em.getTransaction().begin();
        LogPreguntas managedEntity = (LogPreguntas) em.merge(newEntity);
        em.getTransaction().commit();
        entity = managedEntity;
    }
	
    public static LogPreguntas getEntity() {
    	return entity;
    }
}
