/*
 * Created on 2021-10-19 ( 12:45:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.jpa.data;

import javax.persistence.EntityManager;

import com.mindia.carmind.entities.Preguntas;

public class PreguntasData {

	private static Preguntas entity ;

    public static void init(EntityManager em) {
    	// new entity instance
    	Preguntas newEntity = new Preguntas();
		newEntity.setId( Integer.valueOf(100) ) ;
		newEntity.setDescripcion( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setSeccion( Integer.valueOf(100) ) ;

		// save entity in database
        em.getTransaction().begin();
        Preguntas managedEntity = (Preguntas) em.merge(newEntity);
        em.getTransaction().commit();
        entity = managedEntity;
    }
	
    public static Preguntas getEntity() {
    	return entity;
    }
}
