/*
 * Created on 2021-10-19 ( 12:45:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.jpa.data;

import javax.persistence.EntityManager;

import com.mindia.carmind.entities.Secciones;

public class SeccionesData {

	private static Secciones entity ;

    public static void init(EntityManager em) {
    	// new entity instance
    	Secciones newEntity = new Secciones();
		newEntity.setId( Integer.valueOf(100) ) ;
		newEntity.setNombre( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setDescripcion( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;

		// save entity in database
        em.getTransaction().begin();
        Secciones managedEntity = (Secciones) em.merge(newEntity);
        em.getTransaction().commit();
        entity = managedEntity;
    }
	
    public static Secciones getEntity() {
    	return entity;
    }
}
