/*
 * Created on 2021-10-19 ( 12:45:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.jpa.data;

import javax.persistence.EntityManager;

import com.mindia.carmind.entities.Usuarios;

public class UsuariosData {

	private static Usuarios entity ;

    public static void init(EntityManager em) {
    	// new entity instance
    	Usuarios newEntity = new Usuarios();
		newEntity.setId( Integer.valueOf(100) ) ;
		newEntity.setNombre( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setEmpresa( Integer.valueOf(100) ) ;
		newEntity.setAdministrador( Boolean.valueOf(true) ) ;

		// save entity in database
        em.getTransaction().begin();
        Usuarios managedEntity = (Usuarios) em.merge(newEntity);
        em.getTransaction().commit();
        entity = managedEntity;
    }
	
    public static Usuarios getEntity() {
    	return entity;
    }
}
