/*
 * Created on 2021-10-19 ( 12:45:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

import com.mindia.carmind.jpa.tools.JpaTest;

import org.junit.jupiter.api.Test;

public class LogPreguntasJpaTest extends JpaTest {
	
    @Override
    public void initData() {
		// DatabaseData.init(em) has been called before
		// Initialize here other data required for the current test
    }
	
    private LogPreguntas createEntity() {
    	LogPreguntas entity = new LogPreguntas();
		entity.setId( Integer.valueOf(200) ) ;
		entity.setLogEvaluacion( Integer.valueOf(100) ) ;
		entity.setPregunta( Integer.valueOf(100) ) ;
		entity.setRespuesta( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
    	return entity;
    }

    private Object getEntityKey(LogPreguntas entity) {
    	return entity.getId();
    }

    @Test
    public void testPersistFindRemove() {
    	
    	LogPreguntas entity = createEntity();
    	Object key = getEntityKey(entity);

    	// if entity doesn't exist yet
    	if ( find(LogPreguntas.class, key) == null ) {

	    	// Create with 'persist'
    		persistAndRefresh(entity);
    	
			// Find
			LogPreguntas entity2 = find(LogPreguntas.class, key);
			assertNotNull(entity2);
        
			// Remove
			remove(entity2);
			assertNull(find(LogPreguntas.class, key));
		}
    }
    
    @Test
    public void testMergeFindRemove() {
    	
    	LogPreguntas entity = createEntity();
    	Object key = getEntityKey(entity);

    	// Create or update with 'merge'
    	mergeAndRefresh(entity);
    	
    	// Find
    	LogPreguntas entity2 = find(LogPreguntas.class, key);
        assertNotNull(entity2);
        
    	// Remove
    	remove(entity2);
        assertNull(find(LogPreguntas.class, key));
    }

}
