/*
 * Created on 2022-09-29 ( 10:19:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.*;

/**
 * JPA entity class for "Defecto"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="defecto", catalog="carmind" )
public class Defecto implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="log_pregunta_id", nullable=false)
    private int        logPreguntaId ;

    @Column(name="nombre_usuario", nullable=false, length=50)
    private String     nombreUsuario ;

    @Column(name="resuelto", nullable=false)
    private boolean    resuelto ;

    @Column(name="fecha_creacion", nullable=false)
    private LocalDateTime fechaCreacion ;

    @Column(name="vehiculo_id", nullable=false)
    private int        vehiculoId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="log_pregunta_id", referencedColumnName="id", insertable=false, updatable=false)
    private LogPregunta logpregunta ; 

    @ManyToOne
    @JoinColumn(name="vehiculo_id", referencedColumnName="id", insertable=false, updatable=false)
    private Vehiculo   vehiculo ; 


    /**
     * Constructor
     */
    public Defecto() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setLogPreguntaId( int logPreguntaId ) {
        this.logPreguntaId = logPreguntaId ;
    }
    public int getLogPreguntaId() {
        return this.logPreguntaId;
    }

    public void setNombreUsuario( String nombreUsuario ) {
        this.nombreUsuario = nombreUsuario ;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }

    public void setResuelto( boolean resuelto ) {
        this.resuelto = resuelto ;
    }
    public boolean isResuelto() {
        return this.resuelto;
    }

    public void setFechaCreacion( LocalDateTime fechaCreacion ) {
        this.fechaCreacion = fechaCreacion ;
    }
    public LocalDateTime getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setVehiculoId( int vehiculoId ) {
        this.vehiculoId = vehiculoId ;
    }
    public int getVehiculoId() {
        return this.vehiculoId;
    }

    //--- GETTERS FOR LINKS
    public LogPregunta getLogpregunta() {
        return this.logpregunta;
    } 

    public Vehiculo getVehiculo() {
        return this.vehiculo;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(logPreguntaId);
        sb.append("|");
        sb.append(nombreUsuario);
        sb.append("|");
        sb.append(resuelto);
        sb.append("|");
        sb.append(fechaCreacion);
        sb.append("|");
        sb.append(vehiculoId);
        return sb.toString(); 
    } 

}
