/*
 * Created on 2022-10-07 ( 08:33:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.*;

/**
 * JPA entity class for "Defecto"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="defecto", catalog="carmind" )
public class Defecto implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="log_pregunta_id", nullable=false)
    private int        logPreguntaId ;

    @Column(name="nombre_ape_usuario", nullable=false, length=50)
    private String     nombreApeUsuario ;

    @Column(name="fecha_creacion", nullable=false)
    private LocalDateTime fechaCreacion ;

    @Column(name="vehiculo_id", nullable=false)
    private int        vehiculoId ;

    @Column(name="id_usuario")
    private Integer    idUsuario ;

    @Column(name="prioridad", nullable=false)
    private byte       prioridad ;

    @Column(name="estado", nullable=false, length=50)
    private String     estado ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="estado", referencedColumnName="estado", insertable=false, updatable=false)
    private Estado     estado2 ; 

    @ManyToOne
    @JoinColumn(name="log_pregunta_id", referencedColumnName="id", insertable=false, updatable=false)
    private LogPregunta logpregunta ; 

    @ManyToOne
    @JoinColumn(name="id_usuario", referencedColumnName="id", insertable=false, updatable=false)
    private Usuario    usuario ; 

    @ManyToOne
    @JoinColumn(name="vehiculo_id", referencedColumnName="id", insertable=false, updatable=false)
    private Vehiculo   vehiculo ; 


    /**
     * Constructor
     */
    public Defecto() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setLogPreguntaId( int logPreguntaId ) {
        this.logPreguntaId = logPreguntaId ;
    }
    public int getLogPreguntaId() {
        return this.logPreguntaId;
    }

    public void setNombreApeUsuario( String nombreApeUsuario ) {
        this.nombreApeUsuario = nombreApeUsuario ;
    }
    public String getNombreApeUsuario() {
        return this.nombreApeUsuario;
    }

    public void setFechaCreacion( LocalDateTime fechaCreacion ) {
        this.fechaCreacion = fechaCreacion ;
    }
    public LocalDateTime getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setVehiculoId( int vehiculoId ) {
        this.vehiculoId = vehiculoId ;
    }
    public int getVehiculoId() {
        return this.vehiculoId;
    }

    public void setIdUsuario( Integer idUsuario ) {
        this.idUsuario = idUsuario ;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }

    public void setPrioridad( byte prioridad ) {
        this.prioridad = prioridad ;
    }
    public byte getPrioridad() {
        return this.prioridad;
    }

    public void setEstado( String estado ) {
        this.estado = estado ;
    }
    public String getEstado() {
        return this.estado;
    }

    //--- GETTERS FOR LINKS
    public Estado getEstado2() {
        return this.estado2;
    } 

    public LogPregunta getLogpregunta() {
        return this.logpregunta;
    } 

    public Usuario getUsuario() {
        return this.usuario;
    } 

    public Vehiculo getVehiculo() {
        return this.vehiculo;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(logPreguntaId);
        sb.append("|");
        sb.append(nombreApeUsuario);
        sb.append("|");
        sb.append(fechaCreacion);
        sb.append("|");
        sb.append(vehiculoId);
        sb.append("|");
        sb.append(idUsuario);
        sb.append("|");
        sb.append(prioridad);
        sb.append("|");
        sb.append(estado);
        return sb.toString(); 
    } 

}
