/*
 * Created on 2022-02-14 ( 11:21:33 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JPA entity class for "Documento"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="documento", catalog="carmind" )
public class Documento implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Lob
    @Column(name="data", nullable=false, columnDefinition = "mediumblob")
    private byte[]     data ;

    @Column(name="formato", nullable=false, length=6)
    private String     formato ;

    @Column(name="content_type", nullable=false, length=50)
    private String     contentType ;

    @Column(name="vehiculo_id", nullable=false)
    private Integer    vehiculoId ;

    @Column(name="tipo_documento", nullable=false, length=20)
    private String     tipoDocumento ;

    @Column(name="vencimiento", nullable=false)
    private LocalDate       vencimiento ;

    @Column(name="aviso_vencimiento", nullable=false)
    private Boolean    avisoVencimiento ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="vehiculo_id", referencedColumnName="id", insertable=false, updatable=false)
    private Vehiculo   vehiculo ; 

    @ManyToOne
    @JoinColumn(name="tipo_documento", referencedColumnName="nombre", insertable=false, updatable=false)
    private TipoDocumento tipoDocumento2 ; 


    /**
     * Constructor
     */
    public Documento() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setData( byte[] data ) {
        this.data = data ;
    }
    public byte[] getData() {
        return this.data;
    }

    public void setFormato( String formato ) {
        this.formato = formato ;
    }
    public String getFormato() {
        return this.formato;
    }

    public void setContentType( String contentType ) {
        this.contentType = contentType ;
    }
    public String getContentType() {
        return this.contentType;
    }

    public void setVehiculoId( Integer vehiculoId ) {
        this.vehiculoId = vehiculoId ;
    }
    public Integer getVehiculoId() {
        return this.vehiculoId;
    }

    public void setTipoDocumento( String tipoDocumento ) {
        this.tipoDocumento = tipoDocumento ;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }

    public void setVencimiento( LocalDate vencimiento ) {
        this.vencimiento = vencimiento ;
    }
    public LocalDate getVencimiento() {
        return this.vencimiento;
    }

    public void setAvisoVencimiento( Boolean avisoVencimiento ) {
        this.avisoVencimiento = avisoVencimiento ;
    }
    public Boolean getAvisoVencimiento() {
        return this.avisoVencimiento;
    }

    //--- GETTERS FOR LINKS
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    } 

    public TipoDocumento getTipoDocumento2() {
        return this.tipoDocumento2;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        // attribute 'data' not usable (type = byte[])
        sb.append("|");
        sb.append(formato);
        sb.append("|");
        sb.append(contentType);
        sb.append("|");
        sb.append(vehiculoId);
        sb.append("|");
        sb.append(tipoDocumento);
        sb.append("|");
        sb.append(vencimiento);
        sb.append("|");
        sb.append(avisoVencimiento);
        return sb.toString(); 
    } 

}
