/*
 * Created on 2022-06-22 ( 09:55:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Empresa"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="empresa", catalog="carmind" )
public class Empresa implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="nombre", nullable=false, length=50)
    private String     nombre ;

    @Column(name="unidad_distancia", nullable=false, length=20)
    private String     unidadDistancia ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="empresa")
    private List<Evaluacion> evaluacionList ; 

    @OneToMany(mappedBy="empresa")
    private List<Notificaciones> notificacionesList ; 

    @OneToMany(mappedBy="empresa")
    private List<Suscripcion> suscripcionList ; 

    @OneToMany(mappedBy="empresa")
    private List<Usuario> usuarioList ; 

    @OneToMany(mappedBy="empresa")
    private List<Vehiculo> vehiculoList ; 


    /**
     * Constructor
     */
    public Empresa() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setUnidadDistancia( String unidadDistancia ) {
        this.unidadDistancia = unidadDistancia ;
    }
    public String getUnidadDistancia() {
        return this.unidadDistancia;
    }

    //--- GETTERS FOR LINKS
    public List<Evaluacion> getEvaluacionList() {
        return this.evaluacionList;
    } 

    public List<Notificaciones> getNotificacionesList() {
        return this.notificacionesList;
    } 

    public List<Suscripcion> getSuscripcionList() {
        return this.suscripcionList;
    } 

    public List<Usuario> getUsuarioList() {
        return this.usuarioList;
    } 

    public List<Vehiculo> getVehiculoList() {
        return this.vehiculoList;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(unidadDistancia);
        return sb.toString(); 
    } 

}
