/*
 * Created on 2022-02-04 ( 00:09:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Empresa"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="empresa", catalog="carmind" )
public class Empresa implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="nombre", nullable=false, length=50)
    private String     nombre ;

    @Column(name="unidad_distancia", nullable=false, length=20)
    private String     unidadDistancia ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="empresa2")
    private List<Usuario> listOfUsuario ; 

    @OneToMany(mappedBy="empresa")
    private List<Vehiculo> listOfVehiculo ; 


    /**
     * Constructor
     */
    public Empresa() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setUnidadDistancia( String unidadDistancia ) {
        this.unidadDistancia = unidadDistancia ;
    }
    public String getUnidadDistancia() {
        return this.unidadDistancia;
    }

    //--- GETTERS FOR LINKS
    public List<Usuario> getListOfUsuario() {
        return this.listOfUsuario;
    } 

    public List<Vehiculo> getListOfVehiculo() {
        return this.listOfVehiculo;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(unidadDistancia);
        return sb.toString(); 
    } 

}
