/*
 * Created on 2022-10-07 ( 08:33:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Estado"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="estado", catalog="carmind" )
public class Estado implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="estado", nullable=false, length=50)
    private String     estado ;

    //--- ENTITY DATA FIELDS 

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="estado2")
    private List<Defecto> defectoList ; 


    /**
     * Constructor
     */
    public Estado() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setEstado( String estado ) {
        this.estado = estado ;
    }
    public String getEstado() {
        return this.estado;
    }

    //--- GETTERS FOR LINKS
    public List<Defecto> getDefectoList() {
        return this.defectoList;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(estado);
        return sb.toString(); 
    } 

}
