/*
 * Created on 2021-10-19 ( 12:45:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "EvaluacionesPreguntas"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="evaluaciones_preguntas", catalog="carmind" )
public class EvaluacionesPreguntas implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="evaluacion", nullable=false)
    private Integer    evaluacion ;

    @Column(name="pregunta", nullable=false)
    private Integer    pregunta ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="evaluacion", referencedColumnName="id", insertable=false, updatable=false)
    private Evaluaciones evaluaciones ; 

    @ManyToOne
    @JoinColumn(name="pregunta", referencedColumnName="id", insertable=false, updatable=false)
    private Preguntas  preguntas ; 


    /**
     * Constructor
     */
    public EvaluacionesPreguntas() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setEvaluacion( Integer evaluacion ) {
        this.evaluacion = evaluacion ;
    }
    public Integer getEvaluacion() {
        return this.evaluacion;
    }

    public void setPregunta( Integer pregunta ) {
        this.pregunta = pregunta ;
    }
    public Integer getPregunta() {
        return this.pregunta;
    }

    //--- GETTERS FOR LINKS
    public Evaluaciones getEvaluaciones() {
        return this.evaluaciones;
    } 

    public Preguntas getPreguntas() {
        return this.preguntas;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(evaluacion);
        sb.append("|");
        sb.append(pregunta);
        return sb.toString(); 
    } 

}
