/*
 * Created on 2021-11-16 ( 09:54:32 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "EvaluacionPregunta"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="evaluacion_pregunta", catalog="carmind" )
public class EvaluacionPregunta implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="evaluacion", nullable=false)
    private Integer    evaluacion ;

    @Column(name="pregunta", nullable=false)
    private Integer    pregunta ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="evaluacion", referencedColumnName="id", insertable=false, updatable=false)
    private Evaluacion evaluacion2 ; 

    @ManyToOne
    @JoinColumn(name="pregunta", referencedColumnName="id", insertable=false, updatable=false)
    private Pregunta   pregunta2 ; 


    /**
     * Constructor
     */
    public EvaluacionPregunta() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setEvaluacion( Integer evaluacion ) {
        this.evaluacion = evaluacion ;
    }
    public Integer getEvaluacion() {
        return this.evaluacion;
    }

    public void setPregunta( Integer pregunta ) {
        this.pregunta = pregunta ;
    }
    public Integer getPregunta() {
        return this.pregunta;
    }

    //--- GETTERS FOR LINKS
    public Evaluacion getEvaluacion2() {
        return this.evaluacion2;
    } 

    public Pregunta getPregunta2() {
        return this.pregunta2;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(evaluacion);
        sb.append("|");
        sb.append(pregunta);
        return sb.toString(); 
    } 

}
