/*
 * Created on 2021-10-19 ( 12:45:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Evaluaciones"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="evaluaciones", catalog="carmind" )
public class Evaluaciones implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="identificador", nullable=false, length=50)
    private String     identificador ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="evaluaciones")
    private List<LogEvaluaciones> listOfLogEvaluaciones ; 

    @OneToMany(mappedBy="evaluaciones")
    private List<EvaluacionesPreguntas> listOfEvaluacionesPreguntas ; 


    /**
     * Constructor
     */
    public Evaluaciones() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setIdentificador( String identificador ) {
        this.identificador = identificador ;
    }
    public String getIdentificador() {
        return this.identificador;
    }

    //--- GETTERS FOR LINKS
    public List<LogEvaluaciones> getListOfLogEvaluaciones() {
        return this.listOfLogEvaluaciones;
    } 

    public List<EvaluacionesPreguntas> getListOfEvaluacionesPreguntas() {
        return this.listOfEvaluacionesPreguntas;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(identificador);
        return sb.toString(); 
    } 

}
