/*
 * Created on 2022-05-23 ( 10:00:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "LogEvaluacion"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="log_evaluacion", catalog="carmind" )
public class LogEvaluacion implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false)
    private Date       fecha ;

    @Column(name="evaluacion_id", nullable=false)
    private Integer    evaluacionId ;

    @Column(name="vehiculo_id", nullable=false)
    private Integer    vehiculoId ;

    @Column(name="usuario_id", nullable=false)
    private Integer    usuarioId ;

    @Column(name="para_revisar", nullable=false)
    private Boolean    paraRevisar  = false;

    @Column(name="revision_id")
    private Integer    revisionId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="revision_id", referencedColumnName="id", insertable=false, updatable=false)
    private Revision   revision ; 

    @OneToMany(mappedBy="logEvaluacion2")
    private List<LogPregunta> listOfLogPregunta ; 

    @ManyToOne
    @JoinColumn(name="vehiculo_id", referencedColumnName="id", insertable=false, updatable=false)
    private Vehiculo   vehiculo ; 

    @ManyToOne
    @JoinColumn(name="evaluacion_id", referencedColumnName="id", insertable=false, updatable=false)
    private Evaluacion evaluacion ; 

    @ManyToOne
    @JoinColumn(name="usuario_id", referencedColumnName="id", insertable=false, updatable=false)
    private Usuario    usuario ; 


    /**
     * Constructor
     */
    public LogEvaluacion() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setFecha( Date fecha ) {
        this.fecha = fecha ;
    }
    public Date getFecha() {
        return this.fecha;
    }

    public void setEvaluacionId( Integer evaluacionId ) {
        this.evaluacionId = evaluacionId ;
    }
    public Integer getEvaluacionId() {
        return this.evaluacionId;
    }

    public void setVehiculoId( Integer vehiculoId ) {
        this.vehiculoId = vehiculoId ;
    }
    public Integer getVehiculoId() {
        return this.vehiculoId;
    }

    public void setUsuarioId( Integer usuarioId ) {
        this.usuarioId = usuarioId ;
    }
    public Integer getUsuarioId() {
        return this.usuarioId;
    }

    public void setParaRevisar( Boolean paraRevisar ) {
        this.paraRevisar = paraRevisar ;
    }
    public Boolean getParaRevisar() {
        return this.paraRevisar;
    }

    public void setRevisionId( Integer revisionId ) {
        this.revisionId = revisionId ;
    }
    public Integer getRevisionId() {
        return this.revisionId;
    }

    //--- GETTERS FOR LINKS
    public Revision getRevision() {
        return this.revision;
    } 

    public List<LogPregunta> getListOfLogPregunta() {
        return this.listOfLogPregunta;
    } 

    public Vehiculo getVehiculo() {
        return this.vehiculo;
    } 

    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    } 

    public Usuario getUsuario() {
        return this.usuario;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(fecha);
        sb.append("|");
        sb.append(evaluacionId);
        sb.append("|");
        sb.append(vehiculoId);
        sb.append("|");
        sb.append(usuarioId);
        sb.append("|");
        sb.append(paraRevisar);
        sb.append("|");
        sb.append(revisionId);
        return sb.toString(); 
    } 

}
