/*
 * Created on 2022-08-03 ( 12:05:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JPA entity class for "LogEvaluacion"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="log_evaluacion", catalog="carmind" )
public class LogEvaluacion implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="fecha", nullable=false)
    private LocalDateTime fecha ;

    @Column(name="evaluacion_id", nullable=false)
    private int        evaluacionId ;

    @Column(name="vehiculo_id", nullable=false)
    private int        vehiculoId ;

    @Column(name="usuario_id", nullable=false)
    private int        usuarioId ;

    @Column(name="para_revisar", nullable=false)
    private boolean    paraRevisar ;

    @Column(name="revision_id")
    private Integer    revisionId ;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="evaluacion_id", referencedColumnName="id", insertable=false, updatable=false)
    private Evaluacion evaluacion ; 

    @ManyToOne
    @JoinColumn(name="revision_id", referencedColumnName="id", insertable=false, updatable=false)
    private Revision   revision ; 

    @ManyToOne
    @JoinColumn(name="usuario_id", referencedColumnName="id", insertable=false, updatable=false)
    private Usuario    usuario ; 

    @ManyToOne
    @JoinColumn(name="vehiculo_id", referencedColumnName="id", insertable=false, updatable=false)
    private Vehiculo   vehiculo ; 

    @OneToMany(mappedBy="logevaluacion")
    private List<LogPregunta> logpreguntaList ; 


    /**
     * Constructor
     */
    public LogEvaluacion() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setFecha( LocalDateTime fecha ) {
        this.fecha = fecha ;
    }
    public LocalDateTime getFecha() {
        return this.fecha;
    }

    public void setEvaluacionId( int evaluacionId ) {
        this.evaluacionId = evaluacionId ;
    }
    public int getEvaluacionId() {
        return this.evaluacionId;
    }

    public void setVehiculoId( int vehiculoId ) {
        this.vehiculoId = vehiculoId ;
    }
    public int getVehiculoId() {
        return this.vehiculoId;
    }

    public void setUsuarioId( int usuarioId ) {
        this.usuarioId = usuarioId ;
    }
    public int getUsuarioId() {
        return this.usuarioId;
    }

    public void setParaRevisar( boolean paraRevisar ) {
        this.paraRevisar = paraRevisar ;
    }
    public boolean isParaRevisar() {
        return this.paraRevisar;
    }

    public void setRevisionId( Integer revisionId ) {
        this.revisionId = revisionId ;
    }
    public Integer getRevisionId() {
        return this.revisionId;
    }

    //--- GETTERS FOR LINKS
    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    } 
    
    public Revision getRevision() {
        return this.revision;
    } 

    public Usuario getUsuario() {
        return this.usuario;
    } 

    public Vehiculo getVehiculo() {
        return this.vehiculo;
    } 

    public List<LogPregunta> getLogpreguntaList() {
        return this.logpreguntaList;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(fecha);
        sb.append("|");
        sb.append(evaluacionId);
        sb.append("|");
        sb.append(vehiculoId);
        sb.append("|");
        sb.append(usuarioId);
        sb.append("|");
        sb.append(paraRevisar);
        sb.append("|");
        sb.append(revisionId);
        return sb.toString(); 
    } 

}
