/*
 * Created on 2021-12-01 ( 11:35:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "LogEvaluacion"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="log_evaluacion", catalog="carmind" )
public class LogEvaluacion implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false)
    private Date       fecha ;

    @Column(name="evaluacion", nullable=false)
    private Integer    evaluacion ;

    @Column(name="observaciones", length=500)
    private String     observaciones ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="logEvaluacion2")
    private List<LogPregunta> listOfLogPregunta ; 

    @ManyToOne
    @JoinColumn(name="evaluacion", referencedColumnName="id", insertable=false, updatable=false)
    private Evaluacion evaluacion2 ; 

    @OneToMany(mappedBy="logEvaluacion")
    private List<Vehiculo> listOfVehiculo ; 


    /**
     * Constructor
     */
    public LogEvaluacion() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setFecha( Date fecha ) {
        this.fecha = fecha ;
    }
    public Date getFecha() {
        return this.fecha;
    }

    public void setEvaluacion( Integer evaluacion ) {
        this.evaluacion = evaluacion ;
    }
    public Integer getEvaluacion() {
        return this.evaluacion;
    }

    public void setObservaciones( String observaciones ) {
        this.observaciones = observaciones ;
    }
    public String getObservaciones() {
        return this.observaciones;
    }

    //--- GETTERS FOR LINKS
    public List<LogPregunta> getListOfLogPregunta() {
        return this.listOfLogPregunta;
    } 

    public Evaluacion getEvaluacion2() {
        return this.evaluacion2;
    } 

    public List<Vehiculo> getListOfVehiculo() {
        return this.listOfVehiculo;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(fecha);
        sb.append("|");
        sb.append(evaluacion);
        sb.append("|");
        sb.append(observaciones);
        return sb.toString(); 
    } 

}
