/*
 * Created on 2022-02-15 ( 17:29:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JPA entity class for "LogOption"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="log_option", catalog="carmind" )
public class LogOption implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="id_option", nullable=false)
    private Integer    idOption ;

    @Column(name="id_log_pregunta", nullable=false)
    private Integer    idLogPregunta ;

    @Column(name="tick_check", nullable=false)
    private Boolean    tickCheck ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="id_log_pregunta", referencedColumnName="id", insertable=false, updatable=false)
    private LogPregunta logPregunta ; 

    @ManyToOne
    @JoinColumn(name="id_option", referencedColumnName="id", insertable=false, updatable=false)
    private PreguntaOpcion preguntaOpcion ; 


    /**
     * Constructor
     */
    public LogOption() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setIdOption( Integer idOption ) {
        this.idOption = idOption ;
    }
    public Integer getIdOption() {
        return this.idOption;
    }

    public void setIdLogPregunta( Integer idLogPregunta ) {
        this.idLogPregunta = idLogPregunta ;
    }
    public Integer getIdLogPregunta() {
        return this.idLogPregunta;
    }

    public void setTickCheck( Boolean tickCheck ) {
        this.tickCheck = tickCheck ;
    }
    public Boolean getTickCheck() {
        return this.tickCheck;
    }

    //--- GETTERS FOR LINKS
    public LogPregunta getLogPregunta() {
        return this.logPregunta;
    } 

    public PreguntaOpcion getPreguntaOpcion() {
        return this.preguntaOpcion;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(idOption);
        sb.append("|");
        sb.append(idLogPregunta);
        sb.append("|");
        sb.append(tickCheck);
        return sb.toString(); 
    } 

}
