/*
 * Created on 2022-05-23 ( 10:00:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "LogOption"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="log_option", catalog="carmind" )
public class LogOption implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="id_log_pregunta", nullable=false)
    private Integer    idLogPregunta ;

    @Column(name="descripcion", nullable=false, length=50)
    private String     descripcion ;

    @Column(name="tick_check", nullable=false)
    private Boolean    tickCheck ;

    @Column(name="crucial", nullable=false)
    private Boolean    crucial ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="id_log_pregunta", referencedColumnName="id", insertable=false, updatable=false)
    private LogPregunta logPregunta ; 


    /**
     * Constructor
     */
    public LogOption() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setIdLogPregunta( Integer idLogPregunta ) {
        this.idLogPregunta = idLogPregunta ;
    }
    public Integer getIdLogPregunta() {
        return this.idLogPregunta;
    }

    public void setDescripcion( String descripcion ) {
        this.descripcion = descripcion ;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setTickCheck( Boolean tickCheck ) {
        this.tickCheck = tickCheck ;
    }
    public Boolean getTickCheck() {
        return this.tickCheck;
    }

    public void setCrucial( Boolean crucial ) {
        this.crucial = crucial ;
    }
    public Boolean getCrucial() {
        return this.crucial;
    }

    //--- GETTERS FOR LINKS
    public LogPregunta getLogPregunta() {
        return this.logPregunta;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(idLogPregunta);
        sb.append("|");
        sb.append(descripcion);
        sb.append("|");
        sb.append(tickCheck);
        sb.append("|");
        sb.append(crucial);
        return sb.toString(); 
    } 

}
