/*
 * Created on 2022-02-15 ( 17:22:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "LogPregunta"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="log_pregunta", catalog="carmind" )
public class LogPregunta implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="log_evaluacion", nullable=false)
    private Integer    logEvaluacion ;

    @Column(name="id_pregunta", nullable=false)
    private Integer    idPregunta ;

    @Column(name="nota", length=200)
    private String     nota ;

    @Lob
    @Column(name="image")
    private byte[]     image ;

    @Column(name="tick_correcto")
    private Boolean    tickCorrecto ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="log_evaluacion", referencedColumnName="id", insertable=false, updatable=false)
    private LogEvaluacion logEvaluacion2 ; 

    @ManyToOne
    @JoinColumn(name="id_pregunta", referencedColumnName="id", insertable=false, updatable=false)
    private Pregunta   pregunta ; 

    @OneToMany(mappedBy="logPregunta")
    private List<LogOption> listOfLogOption ; 


    /**
     * Constructor
     */
    public LogPregunta() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setLogEvaluacion( Integer logEvaluacion ) {
        this.logEvaluacion = logEvaluacion ;
    }
    public Integer getLogEvaluacion() {
        return this.logEvaluacion;
    }

    public void setIdPregunta( Integer idPregunta ) {
        this.idPregunta = idPregunta ;
    }
    public Integer getIdPregunta() {
        return this.idPregunta;
    }

    public void setNota( String nota ) {
        this.nota = nota ;
    }
    public String getNota() {
        return this.nota;
    }

    public void setImage( byte[] image ) {
        this.image = image ;
    }
    public byte[] getImage() {
        return this.image;
    }

    public void setTickCorrecto( Boolean tickCorrecto ) {
        this.tickCorrecto = tickCorrecto ;
    }
    public Boolean getTickCorrecto() {
        return this.tickCorrecto;
    }

    //--- GETTERS FOR LINKS
    public LogEvaluacion getLogEvaluacion2() {
        return this.logEvaluacion2;
    } 

    public Pregunta getPregunta() {
        return this.pregunta;
    } 

    public List<LogOption> getListOfLogOption() {
        return this.listOfLogOption;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(logEvaluacion);
        sb.append("|");
        sb.append(idPregunta);
        sb.append("|");
        sb.append(nota);
        // attribute 'image' not usable (type = byte[])
        sb.append("|");
        sb.append(tickCorrecto);
        return sb.toString(); 
    } 

}
