/*
 * Created on 2022-08-03 ( 12:05:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JPA entity class for "LogUsoVehiculo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="log_uso_vehiculo", catalog="carmind" )
public class LogUsoVehiculo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="fecha_inicio", nullable=false)
    private LocalDateTime fechaInicio ;

    @Column(name="fecha_fin")
    private LocalDateTime fechaFin ;

    @Column(name="usuario_id", nullable=false)
    private int        usuarioId ;

    @Column(name="vehiculo_id", nullable=false)
    private int        vehiculoId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="usuario_id", referencedColumnName="id", insertable=false, updatable=false)
    private Usuario    usuario ; 

    @ManyToOne
    @JoinColumn(name="vehiculo_id", referencedColumnName="id", insertable=false, updatable=false)
    private Vehiculo   vehiculo ; 


    /**
     * Constructor
     */
    public LogUsoVehiculo() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setFechaInicio( LocalDateTime fechaInicio ) {
        this.fechaInicio = fechaInicio ;
    }
    public LocalDateTime getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaFin( LocalDateTime fechaFin ) {
        this.fechaFin = fechaFin ;
    }
    public LocalDateTime getFechaFin() {
        return this.fechaFin;
    }

    public void setUsuarioId( int usuarioId ) {
        this.usuarioId = usuarioId ;
    }
    public int getUsuarioId() {
        return this.usuarioId;
    }

    public void setVehiculoId( int vehiculoId ) {
        this.vehiculoId = vehiculoId ;
    }
    public int getVehiculoId() {
        return this.vehiculoId;
    }

    //--- GETTERS FOR LINKS
    public Usuario getUsuario() {
        return this.usuario;
    } 

    public Vehiculo getVehiculo() {
        return this.vehiculo;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(fechaInicio);
        sb.append("|");
        sb.append(fechaFin);
        sb.append("|");
        sb.append(usuarioId);
        sb.append("|");
        sb.append(vehiculoId);
        return sb.toString(); 
    } 

}
