/*
 * Created on 2021-12-03 ( 10:36:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * JPA entity class for "Pregunta"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="pregunta", catalog="carmind" )
public class Pregunta implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="descripcion", nullable=false, length=100)
    private String     descripcion ;

    @Column(name="seccion", nullable=false)
    private Integer    seccion ;

    @Column(name="activo", nullable=false)
    private Boolean    activo ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="pregunta2")
    private List<LogPregunta> listOfLogPregunta ; 

    @ManyToOne
    @JoinColumn(name="seccion", referencedColumnName="id", insertable=false, updatable=false)
    @JsonBackReference
    private Seccion    seccion2 ; 

    @OneToMany(mappedBy="pregunta2")
    private List<EvaluacionPregunta> listOfEvaluacionPregunta ; 


    /**
     * Constructor
     */
    public Pregunta() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setDescripcion( String descripcion ) {
        this.descripcion = descripcion ;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setSeccion( Integer seccion ) {
        this.seccion = seccion ;
    }
    public Integer getSeccion() {
        return this.seccion;
    }

    public void setActivo( Boolean activo ) {
        this.activo = activo ;
    }
    public Boolean getActivo() {
        return this.activo;
    }

    //--- GETTERS FOR LINKS
    public List<LogPregunta> getListOfLogPregunta() {
        return this.listOfLogPregunta;
    } 

    public Seccion getSeccion2() {
        return this.seccion2;
    } 

    public List<EvaluacionPregunta> getListOfEvaluacionPregunta() {
        return this.listOfEvaluacionPregunta;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(descripcion);
        sb.append("|");
        sb.append(seccion);
        sb.append("|");
        sb.append(activo);
        return sb.toString(); 
    } 

}
