/*
 * Created on 2021-10-19 ( 12:45:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Preguntas"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="preguntas", catalog="carmind" )
public class Preguntas implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="descripcion", nullable=false, length=100)
    private String     descripcion ;

    @Column(name="seccion", nullable=false)
    private Integer    seccion ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="preguntas")
    private List<LogPreguntas> listOfLogPreguntas ; 

    @ManyToOne
    @JoinColumn(name="seccion", referencedColumnName="id", insertable=false, updatable=false)
    private Secciones  secciones ; 

    @OneToMany(mappedBy="preguntas")
    private List<EvaluacionesPreguntas> listOfEvaluacionesPreguntas ; 


    /**
     * Constructor
     */
    public Preguntas() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setDescripcion( String descripcion ) {
        this.descripcion = descripcion ;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setSeccion( Integer seccion ) {
        this.seccion = seccion ;
    }
    public Integer getSeccion() {
        return this.seccion;
    }

    //--- GETTERS FOR LINKS
    public List<LogPreguntas> getListOfLogPreguntas() {
        return this.listOfLogPreguntas;
    } 

    public Secciones getSecciones() {
        return this.secciones;
    } 

    public List<EvaluacionesPreguntas> getListOfEvaluacionesPreguntas() {
        return this.listOfEvaluacionesPreguntas;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(descripcion);
        sb.append("|");
        sb.append(seccion);
        return sb.toString(); 
    } 

}
