/*
 * Created on 2022-05-23 ( 10:00:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Pregunta"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="pregunta", catalog="carmind" )
public class Pregunta implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="descripcion", nullable=false, length=100)
    private String     descripcion ;

    @Column(name="evaluacion_id", nullable=false)
    private Integer    evaluacionId ;

    @Column(name="tipo", nullable=false, length=50)
    private String     tipo ;

    @Column(name="crucial", nullable=false)
    private Boolean    crucial = false;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="pregunta")
    private List<PreguntaOpcion> listOfPreguntaOpcion ; 

    @ManyToOne
    @JoinColumn(name="tipo", referencedColumnName="codigo", insertable=false, updatable=false)
    private TipoPregunta tipoPregunta ; 

    @ManyToOne
    @JoinColumn(name="evaluacion_id", referencedColumnName="id", insertable=false, updatable=false)
    private Evaluacion evaluacion ; 


    /**
     * Constructor
     */
    public Pregunta() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setDescripcion( String descripcion ) {
        this.descripcion = descripcion ;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setEvaluacionId( Integer evaluacionId ) {
        this.evaluacionId = evaluacionId ;
    }
    public Integer getEvaluacionId() {
        return this.evaluacionId;
    }

    public void setTipo( String tipo ) {
        this.tipo = tipo ;
    }
    public String getTipo() {
        return this.tipo;
    }

    public void setCrucial( Boolean crucial ) {
        this.crucial = crucial ;
    }
    public Boolean getCrucial() {
        return this.crucial;
    }

    //--- GETTERS FOR LINKS
    public List<PreguntaOpcion> getListOfPreguntaOpcion() {
        return this.listOfPreguntaOpcion;
    } 

    public TipoPregunta getTipoPregunta() {
        return this.tipoPregunta;
    } 

    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(descripcion);
        sb.append("|");
        sb.append(evaluacionId);
        sb.append("|");
        sb.append(tipo);
        sb.append("|");
        sb.append(crucial);
        return sb.toString(); 
    } 

}
