/*
 * Created on 2022-03-20 ( 13:53:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JPA entity class for "Revision"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="revision", catalog="carmind" )
public class Revision implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="fecha", nullable=false)
    private LocalDateTime       fecha ;

    @Column(name="usuario_id", nullable=false)
    private Integer    usuarioId ;

    @Column(name="vehiculo_id", nullable=false)
    private Integer    vehiculoId ;

    @Column(name="nota", length=500)
    private String     nota ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Revision() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setFecha( LocalDateTime fecha ) {
        this.fecha = fecha ;
    }
    public LocalDateTime getFecha() {
        return this.fecha;
    }

    public void setUsuarioId( Integer usuarioId ) {
        this.usuarioId = usuarioId ;
    }
    public Integer getUsuarioId() {
        return this.usuarioId;
    }

    public void setVehiculoId( Integer vehiculoId ) {
        this.vehiculoId = vehiculoId ;
    }
    public Integer getVehiculoId() {
        return this.vehiculoId;
    }

    public void setNota( String nota ) {
        this.nota = nota ;
    }
    public String getNota() {
        return this.nota;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(fecha);
        sb.append("|");
        sb.append(usuarioId);
        sb.append("|");
        sb.append(vehiculoId);
        sb.append("|");
        sb.append(nota);
        return sb.toString(); 
    } 

}
