/*
 * Created on 2022-08-03 ( 12:05:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Revision"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="revision", catalog="carmind" )
public class Revision implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="fecha", nullable=false)
    private LocalDateTime fecha ;

    @Column(name="usuario_id", nullable=false)
    private int        usuarioId ;

    @Column(name="vehiculo_id", nullable=false)
    private int        vehiculoId ;

    @Column(name="nota", length=1000)
    private String     nota ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="revision")
    private List<LogEvaluacion> logevaluacionList ; 


    /**
     * Constructor
     */
    public Revision() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setFecha( LocalDateTime fecha ) {
        this.fecha = fecha ;
    }
    public LocalDateTime getFecha() {
        return this.fecha;
    }

    public void setUsuarioId( int usuarioId ) {
        this.usuarioId = usuarioId ;
    }
    public int getUsuarioId() {
        return this.usuarioId;
    }

    public void setVehiculoId( int vehiculoId ) {
        this.vehiculoId = vehiculoId ;
    }
    public int getVehiculoId() {
        return this.vehiculoId;
    }

    public void setNota( String nota ) {
        this.nota = nota ;
    }
    public String getNota() {
        return this.nota;
    }

    //--- GETTERS FOR LINKS
    public List<LogEvaluacion> getLogevaluacionList() {
        return this.logevaluacionList;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(fecha);
        sb.append("|");
        sb.append(usuarioId);
        sb.append("|");
        sb.append(vehiculoId);
        sb.append("|");
        sb.append(nota);
        return sb.toString(); 
    } 

}
