/*
 * Created on 2022-06-22 ( 09:55:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.time.LocalDate;
import javax.persistence.*;

/**
 * JPA entity class for "Suscripcion"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="suscripcion", catalog="carmind" )
public class Suscripcion implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="empresa_id", nullable=false)
    private int        empresaId ;

    @Column(name="fecha_inicio", nullable=false)
    private LocalDate  fechaInicio ;

    @Column(name="fecha_fin", nullable=false)
    private LocalDate  fechaFin ;

    @Column(name="plan", nullable=false)
    private int        plan ;

    @Column(name="es_free_tiral", nullable=false)
    private boolean    esFreeTiral ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="empresa_id", referencedColumnName="id", insertable=false, updatable=false)
    private Empresa    empresa ; 


    /**
     * Constructor
     */
    public Suscripcion() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setEmpresaId( int empresaId ) {
        this.empresaId = empresaId ;
    }
    public int getEmpresaId() {
        return this.empresaId;
    }

    public void setFechaInicio( LocalDate fechaInicio ) {
        this.fechaInicio = fechaInicio ;
    }
    public LocalDate getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaFin( LocalDate fechaFin ) {
        this.fechaFin = fechaFin ;
    }
    public LocalDate getFechaFin() {
        return this.fechaFin;
    }

    public void setPlan( int plan ) {
        this.plan = plan ;
    }
    public int getPlan() {
        return this.plan;
    }

    public void setEsFreeTiral( boolean esFreeTiral ) {
        this.esFreeTiral = esFreeTiral ;
    }
    public boolean isEsFreeTiral() {
        return this.esFreeTiral;
    }

    //--- GETTERS FOR LINKS
    public Empresa getEmpresa() {
        return this.empresa;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(empresaId);
        sb.append("|");
        sb.append(fechaInicio);
        sb.append("|");
        sb.append(fechaFin);
        sb.append("|");
        sb.append(plan);
        sb.append("|");
        sb.append(esFreeTiral);
        return sb.toString(); 
    } 

}
