/*
 * Created on 2022-05-26 ( 09:30:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "TipoPregunta"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="tipo_pregunta", catalog="carmind" )
public class TipoPregunta implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="codigo", nullable=false, length=5)
    private String     codigo ;

    //--- ENTITY DATA FIELDS 
    @Column(name="nombre", nullable=false, length=50)
    private String     nombre ;

    @Column(name="info", nullable=false, length=200)
    private String     info ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="tipoPregunta")
    private List<Pregunta> listOfPregunta ; 

    @OneToMany(mappedBy="tipoPregunta")
    private List<LogPregunta> listOfLogPregunta ; 


    /**
     * Constructor
     */
    public TipoPregunta() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setCodigo( String codigo ) {
        this.codigo = codigo ;
    }
    public String getCodigo() {
        return this.codigo;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setInfo( String info ) {
        this.info = info ;
    }
    public String getInfo() {
        return this.info;
    }

    //--- GETTERS FOR LINKS
    public List<Pregunta> getListOfPregunta() {
        return this.listOfPregunta;
    } 

    public List<LogPregunta> getListOfLogPregunta() {
        return this.listOfLogPregunta;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(codigo);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(info);
        return sb.toString(); 
    } 

}
