/*
 * Created on 2022-03-08 ( 16:20:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "TipoDocumento"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="tipo_documento", catalog="carmind" )
public class TipoDocumento implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="nombre", nullable=false, length=50)
    private String     nombre ;

    //--- ENTITY DATA FIELDS 

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="tipoDocumento2")
    private List<Documento> listOfDocumento ; 


    /**
     * Constructor
     */
    public TipoDocumento() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    //--- GETTERS FOR LINKS
    public List<Documento> getListOfDocumento() {
        return this.listOfDocumento;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(nombre);
        return sb.toString(); 
    } 

}
