/*
 * Created on 2022-06-22 ( 09:55:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "TipoVehiculo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="tipo_vehiculo", catalog="carmind" )
public class TipoVehiculo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="nombre", nullable=false, length=50)
    private String     nombre ;

    //--- ENTITY DATA FIELDS 

    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="tipovehiculo")
    private List<Vehiculo> vehiculoList ; 


    /**
     * Constructor
     */
    public TipoVehiculo() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    //--- GETTERS FOR LINKS
    public List<Vehiculo> getVehiculoList() {
        return this.vehiculoList;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(nombre);
        return sb.toString(); 
    } 

}
