/*
 * Created on 2021-10-19 ( 12:45:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Usuarios"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="usuarios", catalog="carmind" )
public class Usuarios implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="nombre", nullable=false, length=50)
    private String     nombre ;

    @Column(name="empresa", nullable=false)
    private Integer    empresa ;

    @Column(name="administrador", nullable=false)
    private Boolean    administrador ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="empresa", referencedColumnName="id", insertable=false, updatable=false)
    private Empresas   empresas ; 


    /**
     * Constructor
     */
    public Usuarios() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setEmpresa( Integer empresa ) {
        this.empresa = empresa ;
    }
    public Integer getEmpresa() {
        return this.empresa;
    }

    public void setAdministrador( Boolean administrador ) {
        this.administrador = administrador ;
    }
    public Boolean getAdministrador() {
        return this.administrador;
    }

    //--- GETTERS FOR LINKS
    public Empresas getEmpresas() {
        return this.empresas;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(empresa);
        sb.append("|");
        sb.append(administrador);
        return sb.toString(); 
    } 

}
