/*
 * Created on 2022-06-22 ( 09:55:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Usuario"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="usuario", catalog="carmind" )
public class Usuario implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="username", nullable=false, length=50)
    private String     username ;

    @Column(name="nombre", nullable=false, length=50)
    private String     nombre ;

    @Column(name="apellido", nullable=false, length=50)
    private String     apellido ;

    @Column(name="DNI", nullable=false, length=15)
    private String     dni ;

    @Column(name="empresa")
    private Integer    empresa ;

    @Column(name="administrador", nullable=false)
    private boolean    administrador ;

    @Column(name="active", nullable=false)
    private boolean    active ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="usuario")
    private List<LogEvaluacion> logevaluacionList ; 

    @OneToMany(mappedBy="usuario")
    private List<LogUsoVehiculo> logusovehiculoList ; 

    @OneToMany(mappedBy="usuario")
    private List<Notificaciones> notificacionesList ; 

    @ManyToOne
    @JoinColumn(name="empresa", referencedColumnName="id", insertable=false, updatable=false)
    private Empresa    empresa2 ; 

    @OneToMany(mappedBy="usuario")
    private List<Vehiculo> vehiculoList ; 


    /**
     * Constructor
     */
    public Usuario() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setApellido( String apellido ) {
        this.apellido = apellido ;
    }
    public String getApellido() {
        return this.apellido;
    }

    public void setDni( String dni ) {
        this.dni = dni ;
    }
    public String getDni() {
        return this.dni;
    }

    public void setEmpresa( Integer empresa ) {
        this.empresa = empresa ;
    }
    public Integer getEmpresa() {
        return this.empresa;
    }

    public void setAdministrador( boolean administrador ) {
        this.administrador = administrador ;
    }
    public boolean isAdministrador() {
        return this.administrador;
    }

    public void setActive( boolean active ) {
        this.active = active ;
    }
    public boolean isActive() {
        return this.active;
    }

    //--- GETTERS FOR LINKS
    public List<LogEvaluacion> getLogevaluacionList() {
        return this.logevaluacionList;
    } 

    public List<LogUsoVehiculo> getLogusovehiculoList() {
        return this.logusovehiculoList;
    } 

    public List<Notificaciones> getNotificacionesList() {
        return this.notificacionesList;
    } 

    public Empresa getEmpresa2() {
        return this.empresa2;
    } 

    public List<Vehiculo> getVehiculoList() {
        return this.vehiculoList;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(apellido);
        sb.append("|");
        sb.append(dni);
        sb.append("|");
        sb.append(empresa);
        sb.append("|");
        sb.append(administrador);
        sb.append("|");
        sb.append(active);
        return sb.toString(); 
    } 

}
