/*
 * Created on 2021-11-20 ( 12:39:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Usuario"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="usuario", catalog="carmind" )
public class Usuario implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="nombre", nullable=false, length=50)
    private String     nombre ;

    @Column(name="empresa", nullable=false)
    private Integer    empresa ;

    @Column(name="username", nullable=false, length=50)
    private String     username ;

    @Column(name="administrador", nullable=false)
    private Boolean    administrador ;

    @Column(name="DNI", nullable=false, length=15)
    private String     dni ;

    @Column(name="apellido", nullable=false, length=50)
    private String     apellido ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Usuario() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setEmpresa( Integer empresa ) {
        this.empresa = empresa ;
    }
    public Integer getEmpresa() {
        return this.empresa;
    }

    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    public void setAdministrador( Boolean administrador ) {
        this.administrador = administrador ;
    }
    public Boolean getAdministrador() {
        return this.administrador;
    }

    public void setDni( String dni ) {
        this.dni = dni ;
    }
    public String getDni() {
        return this.dni;
    }

    public void setApellido( String apellido ) {
        this.apellido = apellido ;
    }
    public String getApellido() {
        return this.apellido;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(empresa);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(administrador);
        sb.append("|");
        sb.append(dni);
        sb.append("|");
        sb.append(apellido);
        return sb.toString(); 
    } 

}
