/*
 * Created on 2022-08-03 ( 12:05:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Vehiculo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vehiculo", catalog="carmind" )
public class Vehiculo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="nombre", nullable=false, length=50)
    private String     nombre ;

    @Column(name="patente", length=20)
    private String     patente ;

    @Column(name="marca", nullable=false, length=50)
    private String     marca ;

    @Column(name="modelo", nullable=false, length=50)
    private String     modelo ;

    @Column(name="linea", nullable=false, length=4)
    private String     linea ;

    @Column(name="usuario_id_usando")
    private Integer    usuarioIdUsando ;

    @Column(name="empresa_id", nullable=false)
    private int        empresaId ;

    @Column(name="tipo_vehiculo", nullable=false, length=50)
    private String     tipoVehiculo ;

    @Column(name="averiado", nullable=false)
    private boolean    averiado ;

    @Column(name="kilometraje")
    private Integer    kilometraje ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="vehiculo")
    private List<Documento> documentoList ; 

    @OneToMany(mappedBy="vehiculo")
    private List<LogEvaluacion> logevaluacionList ; 

    @OneToMany(mappedBy="vehiculo")
    private List<LogUsoVehiculo> logusovehiculoList ; 

    @ManyToOne
    @JoinColumn(name="empresa_id", referencedColumnName="id", insertable=false, updatable=false)
    private Empresa    empresa ; 

    @ManyToOne
    @JoinColumn(name="tipo_vehiculo", referencedColumnName="nombre", insertable=false, updatable=false)
    private TipoVehiculo tipovehiculo ; 

    @ManyToOne
    @JoinColumn(name="usuario_id_usando", referencedColumnName="id", insertable=false, updatable=false)
    private Usuario    usuario ; 

    @OneToMany(mappedBy="vehiculo")
    private List<VehiculoEvaluacion> vehiculoevaluacionList ; 


    /**
     * Constructor
     */
    public Vehiculo() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setPatente( String patente ) {
        this.patente = patente ;
    }
    public String getPatente() {
        return this.patente;
    }

    public void setMarca( String marca ) {
        this.marca = marca ;
    }
    public String getMarca() {
        return this.marca;
    }

    public void setModelo( String modelo ) {
        this.modelo = modelo ;
    }
    public String getModelo() {
        return this.modelo;
    }

    public void setLinea( String linea ) {
        this.linea = linea ;
    }
    public String getLinea() {
        return this.linea;
    }

    public void setUsuarioIdUsando( Integer usuarioIdUsando ) {
        this.usuarioIdUsando = usuarioIdUsando ;
    }
    public Integer getUsuarioIdUsando() {
        return this.usuarioIdUsando;
    }

    public void setEmpresaId( int empresaId ) {
        this.empresaId = empresaId ;
    }
    public int getEmpresaId() {
        return this.empresaId;
    }

    public void setTipoVehiculo( String tipoVehiculo ) {
        this.tipoVehiculo = tipoVehiculo ;
    }
    public String getTipoVehiculo() {
        return this.tipoVehiculo;
    }

    public void setAveriado( boolean averiado ) {
        this.averiado = averiado ;
    }
    public boolean isAveriado() {
        return this.averiado;
    }

    public void setKilometraje( Integer kilometraje ) {
        this.kilometraje = kilometraje ;
    }
    public Integer getKilometraje() {
        return this.kilometraje;
    }

    //--- GETTERS FOR LINKS
    public List<Documento> getDocumentoList() {
        return this.documentoList;
    } 

    public List<LogEvaluacion> getLogevaluacionList() {
        return this.logevaluacionList;
    } 

    public List<LogUsoVehiculo> getLogusovehiculoList() {
        return this.logusovehiculoList;
    } 

    public Empresa getEmpresa() {
        return this.empresa;
    } 

    public TipoVehiculo getTipovehiculo() {
        return this.tipovehiculo;
    } 

    public Usuario getUsuario() {
        return this.usuario;
    } 

    public List<VehiculoEvaluacion> getVehiculoevaluacionList() {
        return this.vehiculoevaluacionList;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(patente);
        sb.append("|");
        sb.append(marca);
        sb.append("|");
        sb.append(modelo);
        sb.append("|");
        sb.append(linea);
        sb.append("|");
        sb.append(usuarioIdUsando);
        sb.append("|");
        sb.append(empresaId);
        sb.append("|");
        sb.append(tipoVehiculo);
        sb.append("|");
        sb.append(averiado);
        sb.append("|");
        sb.append(kilometraje);
        return sb.toString(); 
    } 

}
