/*
 * Created on 2022-02-02 ( 11:59:19 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JPA entity class for "Vehiculo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vehiculo", catalog="carmind" )
public class Vehiculo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="marca", nullable=false, length=50)
    private String     marca ;

    @Column(name="modelo", nullable=false, length=50)
    private String     modelo ;

    @Column(name="linea", nullable=false, length=4)
    private String     linea ;

    @Column(name="fecha_service")
    private LocalDate       fechaService ;

    @Column(name="usuario_id")
    private Integer    usuarioId ;

    @Column(name="color", nullable=false, length=50)
    private String     color ;

    @Column(name="empresa_id", nullable=false)
    private Integer    empresaId ;

    @Column(name="seguro_pdf")
    private Integer    seguroPdf ;

    @Column(name="vtv_pdf")
    private Integer    vtvPdf ;

    @Column(name="titulo_pdf")
    private Integer    tituloPdf ;

    @Column(name="patente_pdf")
    private Integer    patentePdf ;

    @Column(name="tarjeta_verde_pdf")
    private Integer    tarjetaVerdePdf ;

    @Column(name="ruta_pdf")
    private Integer    rutaPdf ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="empresa_id", referencedColumnName="id", insertable=false, updatable=false)
    private Empresa    empresa ; 

    @ManyToOne
    @JoinColumn(name="usuario_id", referencedColumnName="id", insertable=false, updatable=false)
    private Usuario    usuario ; 

    @OneToMany(mappedBy="vehiculo")
    private List<VehiculoEvaluacion> listOfVehiculoEvaluacion ; 

    @OneToMany(mappedBy="vehiculo")
    private List<LogEvaluacion> listOfLogEvaluacion ; 


    /**
     * Constructor
     */
    public Vehiculo() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setMarca( String marca ) {
        this.marca = marca ;
    }
    public String getMarca() {
        return this.marca;
    }

    public void setModelo( String modelo ) {
        this.modelo = modelo ;
    }
    public String getModelo() {
        return this.modelo;
    }

    public void setLinea( String linea ) {
        this.linea = linea ;
    }
    public String getLinea() {
        return this.linea;
    }

    public void setFechaService( LocalDate fechaService ) {
        this.fechaService = fechaService ;
    }
    public LocalDate getFechaService() {
        return this.fechaService;
    }

    public void setUsuarioId( Integer usuarioId ) {
        this.usuarioId = usuarioId ;
    }
    public Integer getUsuarioId() {
        return this.usuarioId;
    }

    public void setColor( String color ) {
        this.color = color ;
    }
    public String getColor() {
        return this.color;
    }

    public void setEmpresaId( Integer empresaId ) {
        this.empresaId = empresaId ;
    }
    public Integer getEmpresaId() {
        return this.empresaId;
    }

    public void setSeguroPdf( Integer seguroPdf ) {
        this.seguroPdf = seguroPdf ;
    }
    public Integer getSeguroPdf() {
        return this.seguroPdf;
    }

    public void setVtvPdf( Integer vtvPdf ) {
        this.vtvPdf = vtvPdf ;
    }
    public Integer getVtvPdf() {
        return this.vtvPdf;
    }

    public void setTituloPdf( Integer tituloPdf ) {
        this.tituloPdf = tituloPdf ;
    }
    public Integer getTituloPdf() {
        return this.tituloPdf;
    }

    public void setPatentePdf( Integer patentePdf ) {
        this.patentePdf = patentePdf ;
    }
    public Integer getPatentePdf() {
        return this.patentePdf;
    }

    public void setTarjetaVerdePdf( Integer tarjetaVerdePdf ) {
        this.tarjetaVerdePdf = tarjetaVerdePdf ;
    }
    public Integer getTarjetaVerdePdf() {
        return this.tarjetaVerdePdf;
    }

    public void setRutaPdf( Integer rutaPdf ) {
        this.rutaPdf = rutaPdf ;
    }
    public Integer getRutaPdf() {
        return this.rutaPdf;
    }

    //--- GETTERS FOR LINKS
    public Empresa getEmpresa() {
        return this.empresa;
    } 

    public Usuario getUsuario() {
        return this.usuario;
    } 

    public List<VehiculoEvaluacion> getListOfVehiculoEvaluacion() {
        return this.listOfVehiculoEvaluacion;
    } 

    public List<LogEvaluacion> getListOfLogEvaluacion() {
        return this.listOfLogEvaluacion;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(marca);
        sb.append("|");
        sb.append(modelo);
        sb.append("|");
        sb.append(linea);
        sb.append("|");
        sb.append(fechaService);
        sb.append("|");
        sb.append(usuarioId);
        sb.append("|");
        sb.append(color);
        sb.append("|");
        sb.append(empresaId);
        sb.append("|");
        sb.append(seguroPdf);
        sb.append("|");
        sb.append(vtvPdf);
        sb.append("|");
        sb.append(tituloPdf);
        sb.append("|");
        sb.append(patentePdf);
        sb.append("|");
        sb.append(tarjetaVerdePdf);
        sb.append("|");
        sb.append(rutaPdf);
        return sb.toString(); 
    } 

}
