/*
 * Created on 2021-10-19 ( 12:45:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "Vehiculos"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vehiculos", catalog="carmind" )
public class Vehiculos implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="marca", nullable=false, length=50)
    private String     marca ;

    @Column(name="modelo", nullable=false, length=4)
    private String     modelo ;

    @Column(name="linea", nullable=false, length=50)
    private String     linea ;

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_service", nullable=false)
    private Date       fechaService ;

    @Column(name="ultima_evaluacion", nullable=false)
    private Integer    ultimaEvaluacion ;

    @Column(name="color", nullable=false, length=50)
    private String     color ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="ultima_evaluacion", referencedColumnName="id", insertable=false, updatable=false)
    private LogEvaluaciones logEvaluaciones ; 


    /**
     * Constructor
     */
    public Vehiculos() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setMarca( String marca ) {
        this.marca = marca ;
    }
    public String getMarca() {
        return this.marca;
    }

    public void setModelo( String modelo ) {
        this.modelo = modelo ;
    }
    public String getModelo() {
        return this.modelo;
    }

    public void setLinea( String linea ) {
        this.linea = linea ;
    }
    public String getLinea() {
        return this.linea;
    }

    public void setFechaService( Date fechaService ) {
        this.fechaService = fechaService ;
    }
    public Date getFechaService() {
        return this.fechaService;
    }

    public void setUltimaEvaluacion( Integer ultimaEvaluacion ) {
        this.ultimaEvaluacion = ultimaEvaluacion ;
    }
    public Integer getUltimaEvaluacion() {
        return this.ultimaEvaluacion;
    }

    public void setColor( String color ) {
        this.color = color ;
    }
    public String getColor() {
        return this.color;
    }

    //--- GETTERS FOR LINKS
    public LogEvaluaciones getLogEvaluaciones() {
        return this.logEvaluaciones;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(marca);
        sb.append("|");
        sb.append(modelo);
        sb.append("|");
        sb.append(linea);
        sb.append("|");
        sb.append(fechaService);
        sb.append("|");
        sb.append(ultimaEvaluacion);
        sb.append("|");
        sb.append(color);
        return sb.toString(); 
    } 

}
