/*
 * Created on 2022-01-12 ( 14:48:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "VehiculoEvaluacion"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vehiculo_evaluacion", catalog="carmind" )
public class VehiculoEvaluacion implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="vehiculo_id", nullable=false)
    private Integer    vehiculoId ;

    @Column(name="evaluacion_id", nullable=false)
    private Integer    evaluacionId ;

    @Column(name="intervalo_dias", nullable=false)
    private Integer    intervaloDias ;

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", nullable=false)
    private Date       fechaInicio ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="vehiculo_id", referencedColumnName="id", insertable=false, updatable=false)
    private Vehiculo   vehiculo ; 

    @ManyToOne
    @JoinColumn(name="evaluacion_id", referencedColumnName="id", insertable=false, updatable=false)
    private Evaluacion evaluacion ; 


    /**
     * Constructor
     */
    public VehiculoEvaluacion() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setVehiculoId( Integer vehiculoId ) {
        this.vehiculoId = vehiculoId ;
    }
    public Integer getVehiculoId() {
        return this.vehiculoId;
    }

    public void setEvaluacionId( Integer evaluacionId ) {
        this.evaluacionId = evaluacionId ;
    }
    public Integer getEvaluacionId() {
        return this.evaluacionId;
    }

    public void setIntervaloDias( Integer intervaloDias ) {
        this.intervaloDias = intervaloDias ;
    }
    public Integer getIntervaloDias() {
        return this.intervaloDias;
    }

    public void setFechaInicio( Date fechaInicio ) {
        this.fechaInicio = fechaInicio ;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    //--- GETTERS FOR LINKS
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    } 

    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(vehiculoId);
        sb.append("|");
        sb.append(evaluacionId);
        sb.append("|");
        sb.append(intervaloDias);
        sb.append("|");
        sb.append(fechaInicio);
        return sb.toString(); 
    } 

}
