/*
 * Created on 2022-05-31 ( 16:07:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JPA entity class for "Version"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="version", catalog="carmind" )
public class Version implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="storeVersion", nullable=false, length=15)
    private String     storeversion ;

    @Column(name="storeReleaseNotes", length=1000)
    private String     storereleasenotes ;

    @Column(name="storeType", nullable=false, length=50)
    private String     storetype ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Version() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setStoreversion( String storeversion ) {
        this.storeversion = storeversion ;
    }
    public String getStoreversion() {
        return this.storeversion;
    }

    public void setStorereleasenotes( String storereleasenotes ) {
        this.storereleasenotes = storereleasenotes ;
    }
    public String getStorereleasenotes() {
        return this.storereleasenotes;
    }

    public void setStoretype( String storetype ) {
        this.storetype = storetype ;
    }
    public String getStoretype() {
        return this.storetype;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(storeversion);
        sb.append("|");
        sb.append(storereleasenotes);
        sb.append("|");
        sb.append(storetype);
        return sb.toString(); 
    } 

}
