/*
 * Created on 2022-02-14 ( 11:21:33 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JPA entity class for "Version"
 *
 * @author Pelli
 *
 */
@Entity
@Table(name="version", catalog="carmind" )
public class Version implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="storeVersion", nullable=false, unique = true)
    private String    storeVersion ;

    @Column(name="storeReleaseNotes", nullable=true)
    private String storeReleaseNotes ;

    @Column(name="storeType", nullable=false)
    private String storeType;

    /**
     * Constructor
     */
    public Version() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public Integer getId() {
        return this.id;
    }

    public void setStoreVersion( String storeVersion ) {
        this.storeVersion = storeVersion ;
    }
    public String getStoreVersion() {
        return this.storeVersion;
    }

    public void setStoreReleaseNotes( String storeReleaseNotes ) {
        this.storeReleaseNotes = storeReleaseNotes ;
    }
    public String getStoreReleaseNotes() {
        return this.storeReleaseNotes;
    }

    public void setStoreType( String storeType ) {
        this.storeType = storeType ;
    }
    public String getStoreType() {
        return this.storeType;
    }

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(storeVersion);
        sb.append("|");
        sb.append(storeReleaseNotes);
        sb.append("|");
        sb.append(storeType);
        return sb.toString(); 
    } 

}
