/*
 * Created on 2022-06-22 ( 09:55:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.mindia.carmind.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Version"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="version", catalog="carmind" )
public class Version implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private int        id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="store_release_notes", length=1000)
    private String     storeReleaseNotes ;

    @Column(name="store_type", nullable=false, length=50)
    private String     storeType ;

    @Column(name="store_version", nullable=false, length=15)
    private String     storeVersion ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Version() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( int id ) {
        this.id = id ;
    }
    public int getId() {
        return this.id;
    }

    public void setStoreReleaseNotes( String storeReleaseNotes ) {
        this.storeReleaseNotes = storeReleaseNotes ;
    }
    public String getStoreReleaseNotes() {
        return this.storeReleaseNotes;
    }

    public void setStoreType( String storeType ) {
        this.storeType = storeType ;
    }
    public String getStoreType() {
        return this.storeType;
    }

    public void setStoreVersion( String storeVersion ) {
        this.storeVersion = storeVersion ;
    }
    public String getStoreVersion() {
        return this.storeVersion;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(storeReleaseNotes);
        sb.append("|");
        sb.append(storeType);
        sb.append("|");
        sb.append(storeVersion);
        return sb.toString(); 
    } 

}
